name = "Greek"
uuid = "72b824a7-2b4a-40fa-944c-ac4f345dc63a"
authors = ["nsmith "]
version = "0.1.0"

[deps]
Orthography = "0b4c9448-09b0-4e78-95ea-3eb3328be36d"


[compat]
DocStringExtensions = "0.8"
Documenter = "0.26"
Orthography = "0.4"
julia = "1.5"